version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - tagliatelle
    - tagalign
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Memory optimization not needed; prefer logical field ordering.
    tagliatelle:
      case:
        rules:
          json: camel
          yaml: snake
          toml: snake
        overrides:
          # OpenAI API-compatible types use snake_case.
          - pkg: providers
            ignore: true
          - pkg: providers/platform
            ignore: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mozilla-ai/any-llm-go)
        - blank
        - dot
        - localmodule
    golines:
      max-len: 120

issues:
  fix: true

output:
  formats:
    text:
      path: stderr
  sort-order:
    - severity
    - file
    - linter

run:
  timeout: 5m
  tests: true
  relative-path-mode: gomod
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
